export enum Status {
  WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT",
  WAITING_CONFIRMATION = "WAITING_CONFIRMATION",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
  CANCELED = "CANCELED",
  DONE = "DONE",
}
